version: '3.8'

services:
  # Migration service
  migrations:
    build: .
    container_name: senya_migrations
    volumes:
      - .:/app
      - ./backups:/backups
    environment:
      - ENVIRONMENT=production
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    command: ["./migrate.sh"]
    restart: "no"

  # Backend service
  backend:
    build: .
    container_name: senya_backend_prod
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    depends_on:
      migrations:
        condition: service_completed_successfully
    restart: unless-stopped
    command: ["./start.sh"]

volumes:
  postgres_data: 