services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://senya:senya@db:5432/senya_db
    depends_on:
      - db
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=senya
      - POSTGRES_PASSWORD=senya
      - POSTGRES_DB=senya_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: 