#token 
ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_DAYS = 7

#note format
NOTE_FORMAT_MARKDOWN = "markdown"
NOTE_FORMAT_TEXT = "text"
NOTE_FORMAT_HTML = "html"
NOTE_FORMAT_PDF = "pdf"
NOTE_FORMAT_IMAGE = "image"
NOTE_FORMAT_AUDIO = "audio"