"""added cascade to note folder

Revision ID: 3e40f330ba95
Revises: 68f3d6022b21
Create Date: 2025-05-31 13:21:24.162325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e40f330ba95'
down_revision: Union[str, None] = '68f3d6022b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('note_folder_id_fkey', 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'note_folder', ['folder_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('note_folder_parent_id_fkey', 'note_folder', type_='foreignkey')
    op.create_foreign_key(None, 'note_folder', 'note_folder', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note_folder', type_='foreignkey')
    op.create_foreign_key('note_folder_parent_id_fkey', 'note_folder', 'note_folder', ['parent_id'], ['id'])
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.create_foreign_key('note_folder_id_fkey', 'note', 'note_folder', ['folder_id'], ['id'])
    # ### end Alembic commands ###
