"""initial_setup_after_reset

Revision ID: a082b6203119
Revises: 6f5e0c77dfd1
Create Date: 2025-06-01 01:26:45.155525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a082b6203119'
down_revision: Union[str, None] = '6f5e0c77dfd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
