"""add notes and note folder

Revision ID: f2f3a9fb7e87
Revises: 49e1f6b6225d
Create Date: 2025-01-24 21:52:43.028243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f3a9fb7e87'
down_revision: Union[str, None] = '49e1f6b6225d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
